// src/constants.js

export const ADMIN_PASSWORD = 'Naku'

// ─── Personajes ───────────────────────────────────────────────────────────────
// tipoAccion: 'proteger' | 'revelar' | 'paralizar' | 'votar_doble' | 'pasiva_rena' | 'pasiva_rika' | 'asesinar'
export const PERSONAJES = [
  {
    id: 'keiichi',
    nombre: 'Keiichi Maebara',
    avatar: '/avatares/keiichi.png',
    color: 'from-blue-900/40 to-blue-950',
    borderColor: 'border-blue-700/50',
    textColor: 'text-blue-300',
    accentColor: 'bg-blue-600',
    descripcion: 'El chico nuevo de Hinamizawa',
    objeto: 'Bate de Oro',
    descripcionObjeto: 'Elige a un compañero para protegerlo esta noche. Si el asesino lo ataca, el golpe se anula.',
    tipoAccion: 'proteger',
    usos: 1,
    emoji: '⚾',
    // La acción necesita elegir un objetivo entre todos los vivos (incluido uno mismo)
    puedeElegirseAsiMismo: true,
  },
  {
    id: 'rena',
    nombre: 'Rena Ryuuguu',
    avatar: '/avatares/rena.png',
    color: 'from-pink-900/40 to-pink-950',
    borderColor: 'border-pink-700/50',
    textColor: 'text-pink-300',
    accentColor: 'bg-pink-600',
    descripcion: '¡Me lo llevo a casa!',
    objeto: 'Machete del Vertedero',
    descripcionObjeto: 'Pasiva. Si el pueblo la lincha siendo inocente, arrastra a la tumba a quien más votos le dio.',
    tipoAccion: 'pasiva_rena',
    usos: 1,
    emoji: '🔪',
    puedeElegirseAsiMismo: false,
  },
  {
    id: 'mion',
    nombre: 'Mion Sonozaki',
    avatar: '/avatares/mion.png',
    color: 'from-emerald-900/40 to-emerald-950',
    borderColor: 'border-emerald-700/50',
    textColor: 'text-emerald-300',
    accentColor: 'bg-emerald-600',
    descripcion: 'Líder del Club de Juegos',
    objeto: 'Rotulador del Club',
    descripcionObjeto: 'Tu voto diurno vale el doble (peso 2) en la primera votación que participes.',
    tipoAccion: 'votar_doble',
    usos: 1,
    emoji: '✍️',
    puedeElegirseAsiMismo: false,
  },
  {
    id: 'rika',
    nombre: 'Furude Rika',
    avatar: '/avatares/rika.png',
    color: 'from-indigo-900/40 to-indigo-950',
    borderColor: 'border-indigo-700/50',
    textColor: 'text-indigo-300',
    accentColor: 'bg-indigo-600',
    descripcion: 'Miko del Santuario Furude',
    objeto: 'Fragmento Temporal',
    descripcionObjeto: 'Elige a un jugador esta noche. Al amanecer recibirás un informe secreto: es Aldeano o es el Asesino.',
    tipoAccion: 'revelar',
    usos: 1,
    emoji: '⏳',
    puedeElegirseAsiMismo: false,
  },
  {
    id: 'satoko',
    nombre: 'Houjou Satoko',
    avatar: '/avatares/satoko.png',
    color: 'from-amber-900/40 to-amber-950',
    borderColor: 'border-amber-700/50',
    textColor: 'text-amber-300',
    accentColor: 'bg-amber-600',
    descripcion: 'Maestra de las trampas',
    objeto: 'Trampa de Alambre',
    descripcionObjeto: 'Instala trampas en la puerta de un sospechoso. Al amanecer sabrás si usó su habilidad o no esa noche.',
    tipoAccion: 'rastrear',
    usos: 2,
    emoji: '🪤',
    puedeElegirseAsiMismo: false,
  },
  {
    id: 'shion',
    nombre: 'Shion Sonozaki',
    avatar: '/avatares/shion.png',
    color: 'from-violet-900/40 to-violet-950',
    borderColor: 'border-violet-700/50',
    textColor: 'text-violet-300',
    accentColor: 'bg-violet-600',
    descripcion: 'Gemela de Mion',
    objeto: 'Táser de Mord',
    descripcionObjeto: 'Paraliza a un sospechoso esta noche. Su habilidad o asesinato quedan completamente anulados.',
    tipoAccion: 'paralizar',
    usos: 1,
    emoji: '⚡',
    puedeElegirseAsiMismo: false,
  },
]

export const CATEGORIAS = [
  { id: 'principal',      label: 'Platos Principales', emoji: '🍱' },
  { id: 'acompanamiento', label: 'Acompañamientos',    emoji: '🥢' },
  { id: 'postre',         label: 'Postres',             emoji: '🍡' },
]

export const VISTAS = {
  LOGIN:   'login',
  MENU:    'menu',
  DETALLE: 'detalle',
  COMANDA: 'comanda',
  ADMIN:   'admin',
  JUEGO:   'juego',
}

export const FASES = {
  ESPERA:     'espera',
  DIA:        'dia',
  VOTACION:   'votacion',
  NOCHE:      'noche',
  FINALIZADO: 'finalizado',
}
